# This workflow runs on every push to the main branch and on pull requests.
# It checks out the repository, sets up Node.js, installs dependencies,
# and runs the format command defined in the frontend package.
name: Format Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run Format Command
        working-directory: ./frontend
        run: npm run format
